FROM mysql:5.7

MAINTAINER Alexey Borovkov <alexey.b@turing.com>

ENV MYSQL_DATABASE 'turing'
ENV MYSQL_ROOT_PASSWORD 'root'
ENV MYSQL_USER 'turing'
ENV MYSQL_PASSWORD 'turing'

COPY ./database/dump.sql /docker-entrypoint-initdb.d/dump.sql

